language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - git submodule update --init --recursive
  - whoami
  - pwd
  - ls
  - git status
  - ls ~
  - echo $HOME
  - env
  - BASEDIR=$(pwd)
  - echo BASEDIR $BASEDIR
  - wget https://www.python.org/ftp/python/3.4.4/python-3.4.4-macosx10.6.pkg
  - sudo installer -pkg python-3.4.4-macosx10.6.pkg -target /
  - python3 -V
  - wget https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz
  - tar -xf virtualenv-14.0.6.tar.gz
  - virtualenv-14.0.6/virtualenv.py -p python3 ~/env
  - source ~/env/bin/activate
  - pip install -U pip
  - pip install -U setuptools
  - pip install wheel
  - pip install numpy

script:
  - echo hello
  - env
  - mkdir build
  - cd build
  - cmake -DBUILD_PYTHON_WRAPPERS=ON ..
  - make -j 4
  - make install
  - source ../dist/bin/activate.sh
  - deepcl_unittests tests=-DATA*:SLOW*:testClBlas*:testDeepCL.basic:testupdateweights*:testforward*:testsimpleconvolvenet*:testlogicaloperators*:testbackward*:testsinglebatch*:EXCLUDED*:testpoolingforward*:testCopyBlock.basic:testCopyLocal.basic:testactivationforward*:testdropoutforward*:testsgd.basic:testCLMathWrapper.sqrt
  - cd ../python
  - source ~/env/bin/activate
  - python setup.py install
  - python test_squaremax.py

notifications:
  email:
    on_success: never
    on_failure: never

